DROP TABLE USERS;

CREATE TABLE USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FIRSTNAME VARCHAR(20) NOT NULL,
  LASTNAME VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  USERNAME VARCHAR(20) NOT NULL,
  PASSWORD CHAR(16) NOT NULL,
  CREATE_AT DATETIME NOT NULL
);
